'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/api';
type Payment={id:number;memberName:string;plan:string;amount_cents:number;paid_at:string;operator:string};
type Membership={id:number;memberName:string;plan:string;price_cents:number;paid:number;status:string};
export default function Payments(){
  const [payments,setPayments]=useState<Payment[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[selected,setSelected]=useState(''),[amount,setAmount]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load(){setPayments(await api<Payment[]>('payments'));setMemberships(await api<Membership[]>('memberships'));}
  useEffect(()=>{api<Payment[]>('payments').then(setPayments).catch(e=>setMessage(e.message));api<Membership[]>('memberships').then(setMemberships).catch(e=>setMessage(e.message));},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api('payments','POST',{membershipId:Number(selected),amountCents:Math.round(Number(amount)*100)});await load();setMessage('Pago confirmado.');setSelected('');setAmount('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <div className="membership-container"><h1>Pagos · US$ (USD)</h1><div className="membership-card"><h2>Confirmar pago completo</h2><form onSubmit={submit}><div className="form-group"><label htmlFor="membership">Membresía pendiente de pago</label><select id="membership" required value={selected} onChange={e=>{setSelected(e.target.value);const m=memberships.find(m=>m.id===Number(e.target.value));setAmount(m?String(m.price_cents/100):'');}}><option value="">Selecciona una membresía</option>{memberships.filter(m=>!m.paid).map(m=><option key={m.id} value={m.id}>#{m.id} {m.memberName} · {m.plan} · {m.status}</option>)}</select></div><div className="form-group"><label htmlFor="amount">Monto US$</label><input id="amount" required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><button className="membership-button" disabled={busy}>Confirmar pago</button></form><p role="status">{message}</p></div><div className="membership-card membership-table-wrapper"><table className="membership-table"><thead><tr><th>Miembro</th><th>Plan</th><th>Monto US$</th><th>Fecha (La Paz)</th><th>Operador</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.memberName}</td><td>{p.plan}</td><td>US${(p.amount_cents/100).toFixed(2)}</td><td>{new Date(p.paid_at).toLocaleString('es-BO',{timeZone:'America/La_Paz'})}</td><td>{p.operator}</td></tr>)}</tbody></table></div></div>;
}
